# Improvement Agent Configuration Constants

# Analysis Thresholds
SEMANTIC_THRESHOLD = 0.70
GRAPH_THRESHOLD = 0.75
LANDSCAPE_THRESHOLD = 0.50  # 0 to 1 scale
DENSITY_THRESHOLD = 10
NOVELTY_SCORE_THRESHOLD = 60.0
NON_OBVIOUSNESS_SCORE_THRESHOLD = 60.0
PATENTABILITY_SCORE_THRESHOLD = 55.0

# Result Reporting Constants
TOP_N_OVERLAPPING = 3
