import logging
import numpy as np

logger = logging.getLogger(__name__)

def rerank_hits(
    hits: list, 
    embeddings: np.ndarray, 
    preds: np.ndarray, 
    pid_to_idx: dict, 
    mode: str = "novelty",
    semantic_weight: float = 0.7, 
    novelty_weight: float = 0.3
) -> list:
    """
    Rerank patents by blending semantic similarity and GNN structural similarity / predictions.
    
    Parameters:
        hits: List of hit dictionaries from retrieval + KG expansion.
        embeddings: Node embeddings generated by the GNN model forward pass (shape: [N, 64]).
        preds: Novelty predictions generated by the GNN model output head (shape: [N, 1]).
        pid_to_idx: Dictionary mapping patent_id -> node_index in the GNN matrices.
        mode: "novelty" to use GNN novelty prediction, "graph_sim" to use centroid similarity.
        semantic_weight: Weight for the semantic score.
        novelty_weight: Weight for the GNN graph score.
        
    Returns:
        List of reranked hit dictionaries with updated scores and ranks.
    """
    if not hits:
        return hits

    # 1. Identify indices of candidate patents (the patents in the hits list)
    candidate_indices = []
    valid_hits = []
    
    for i, hit in enumerate(hits):
        pid = hit.get("patent_id", "")
        if pid in pid_to_idx:
            candidate_indices.append(pid_to_idx[pid])
            valid_hits.append(hit)
        else:
            # Fallback for hits missing from GNN node map: assign neutral scores
            hit["graph_score"] = 0.5
            hit["novelty_score"] = 0.5
            sem = hit.get("semantic_score") or 0.0
            hit["combined_score"] = round(semantic_weight * sem + novelty_weight * 0.5, 6)
            hit["gnn_mode"] = mode
            hit["rank_change"] = 0
            
    # If no hits mapped to the graph nodes, just sort by semantic similarity
    if not candidate_indices:
        hits.sort(key=lambda h: h.get("semantic_score") or 0.0, reverse=True)
        for rank, hit in enumerate(hits, start=1):
            hit["rank"] = rank
            hit["novelty_score"] = 0.5
            hit["graph_score"] = 0.5
            hit["rank_change"] = 0
        return hits
        
    candidate_indices = np.array(candidate_indices)
    graph_scores = np.zeros(len(valid_hits), dtype=np.float32)
    
    # 2. Calculate GNN structural score based on mode
    if mode == "novelty":
        # Extract predicted novelty from GNN head
        raw_preds = preds[candidate_indices].squeeze()
        if len(candidate_indices) == 1:
            raw_preds = np.array([raw_preds])
            
        lo, hi = raw_preds.min(), raw_preds.max()
        if hi > lo:
            graph_scores = (raw_preds - lo) / (hi - lo)
        else:
            graph_scores = np.full_like(raw_preds, 0.5)
            
    elif mode == "graph_sim":
        # Compute centroid similarity in GNN embedding space
        norms = np.linalg.norm(embeddings, axis=1, keepdims=True) + 1e-8
        normed_embs = embeddings / norms
        
        # Calculate centroid of all nodes in the expanded subgraph
        centroid = normed_embs.mean(axis=0)
        centroid = centroid / (np.linalg.norm(centroid) + 1e-8)
        
        # Calculate cosine similarity of candidate embeddings against the centroid
        candidate_embs = normed_embs[candidate_indices]
        cos_sims = candidate_embs @ centroid
        if len(candidate_indices) == 1:
            cos_sims = np.array([cos_sims])
            
        # Min-max scale similarities to [0, 1]
        lo, hi = cos_sims.min(), cos_sims.max()
        if hi > lo:
            graph_scores = (cos_sims - lo) / (hi - lo)
        else:
            graph_scores = np.full_like(cos_sims, 0.5)
            
    else:
        # Default fallback
        graph_scores = np.full(len(valid_hits), 0.5, dtype=np.float32)

    # 3. Blending and re-ranking
    for idx, hit in enumerate(valid_hits):
        g_score = float(graph_scores[idx])
        sem_score = hit.get("semantic_score")
        if sem_score is None:
            # Expanded patents have no pre-computed semantic score, default to 0.0 or handle in caller
            sem_score = 0.0
            
        combined_score = semantic_weight * sem_score + novelty_weight * g_score
        
        hit["graph_score"] = round(g_score, 6)
        hit["novelty_score"] = round(g_score, 6)
        hit["combined_score"] = round(combined_score, 6)
        hit["gnn_mode"] = mode

    # Sort hits by combined_score descending
    hits.sort(key=lambda h: h.get("combined_score") or 0.0, reverse=True)
    
    # 4. Update rank and calculate rank change
    for new_rank, hit in enumerate(hits, start=1):
        hit["rank"] = new_rank
        faiss_rank = hit.get("faiss_rank", -1)
        if faiss_rank > 0:
            hit["rank_change"] = int(faiss_rank - new_rank)
        else:
            hit["rank_change"] = 0

    return hits
